### ISSUE TITLE
SelectBooleanCheckbox: Wrong style with Barcelona

### ISSUE THREAD

**Issue by Rapster** [primefaces/layouts#154]
Using this sample with Barcelona
```
<div class="card card-w-title">
    <h1>Checkboxes</h1>
    <p:selectBooleanCheckbox value="1" itemLabel="Xbox One" />
    <br />
    <p:selectBooleanCheckbox value="3" itemLabel="PS+" />
    <br />
    <p:selectBooleanCheckbox value="2" itemLabel="Wii U"/>
</div>
```

Results into this:
![image](https://user-images.githubusercontent.com/7521311/34828970-883fe358-f6df-11e7-8546-a54df52bd9fb.png)

You set a width and height to the wrong place. See _forms.scss:
```scss
.ui-chkbox {
        display: inline-block;
        vertical-align: middle;
        width: $iconWidth - 2px;
        height: $iconHeight - 2px;
        cursor: default;
        margin: 0 4px 0 0;
        ...
}
```

On PF showcase, it shows these are set on `.ui-chkbox .ui-chkbox-box`. Although, once this fix is done, try to select/unselect checkbox you'll see a gap showing up.

@onursenture @mertsincan Could you fix this one please?
